#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_FILE = ROOT / "docs" / "IMPLEMENTATION_STATUS.generated.md"


CHECKS = [
    ("WS subscriptions table wiring", "template.yaml", "WS_SUBSCRIPTIONS_TABLE"),
    ("Async action timeout sweeper", "template.yaml", "ActionTimeoutSweeperFunction"),
    ("Policy evaluator module", "layers/shared/python/agent_hub/auto_approve_policy.py", "evaluate_auto_approve"),
    ("Docs contract script", "scripts/verify_docs_contracts.py", "validate_tool_payload"),
    ("Contracts package", "layers/shared/python/agent_hub/contracts/__init__.py", "validate_tool_payload"),
    ("E2E workflow", ".github/workflows/e2e-contracts.yml", "-m e2e"),
]


def _has(path: Path, needle: str) -> bool:
    if not path.exists():
        return False
    return needle in path.read_text(encoding="utf-8")


def build_doc() -> str:
    lines = [
        "# Implementation Status (Generated)",
        "",
        "| Check | Status |",
        "|---|---|",
    ]

    for label, rel_path, needle in CHECKS:
        ok = _has(ROOT / rel_path, needle)
        lines.append(f"| {label} | {'PASS' if ok else 'FAIL'} |")

    lines.append("")
    lines.append("This file is generated by `scripts/generate_implementation_status.py`.")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated output differs")
    args = parser.parse_args()

    generated = build_doc()

    if args.check:
        existing = OUT_FILE.read_text(encoding="utf-8") if OUT_FILE.exists() else ""
        if existing != generated:
            print("Implementation status doc is out of date. Re-run generator.")
            return 1
        print("Implementation status doc is up to date.")
        return 0

    OUT_FILE.write_text(generated, encoding="utf-8")
    print(f"Wrote {OUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
