"""LiveKit Agent worker for Marvain.

This runs the realtime voice experience (OpenAI Realtime API) and talks to the Hub
via REST/WebSocket as a "satellite".

Architecture:
- LiveKit "room" name = Marvain "space_id" (UUID)
- One space can have many sequential rooms over time (ephemeral media sessions)
- Transcripts are stored in the Hub's events table, keyed by space_id
- When agent is recreated on rejoin, it can query Hub for prior context (Phase 2)

Based on LiveKit's Voice AI quickstart (realtime model).
"""

from __future__ import annotations

import asyncio
import logging
import os
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

import requests
from agent_hub.memory_classifier import MemoryClassifierUnavailable, classify_memory_event
from agent_hub.personas import DEFAULT_AGENT_PERSONA_NAME
from dotenv import load_dotenv
from livekit import agents, rtc
from livekit.agents import Agent, AgentServer, AgentSession, room_io
from livekit.plugins import noise_cancellation, openai

if TYPE_CHECKING:
    pass

load_dotenv(os.getenv("ENV_FILE", ".env"))


def _ensure_stdio_open_and_inheritable() -> None:
    """Ensure stdio fds are valid and inherited by child processes.

    LiveKit Agents uses subprocesses for job execution. If this worker is launched
    with closed or close-on-exec stdio fds (common when daemonized), child Python
    processes can crash at startup with:
      init_sys_streams: can't initialize sys standard streams (Bad file descriptor)

    We defensively:
    - reopen missing fds to /dev/null
    - mark 0/1/2 inheritable so exec() children keep them
    """

    import os

    for fd in (0, 1, 2):
        try:
            os.fstat(fd)
        except OSError:
            newfd = os.open(os.devnull, os.O_RDWR)
            try:
                os.dup2(newfd, fd)
            finally:
                os.close(newfd)

        try:
            os.set_inheritable(fd, True)
        except OSError:
            # Best-effort; if the platform rejects, we'll still have valid fds.
            pass


_ensure_stdio_open_and_inheritable()

logger = logging.getLogger("marvain.agent_worker")

VISUAL_TRUTHFULNESS_GUARD = """# Vision / Sensor Truthfulness
You do not have direct video, screenshot, image, or file visual access in this session unless the prompt includes a section named "Current Session Visual Observations".
If that section is absent, do not claim that you can see the room, screen, camera feed, screenshot, image, video, or file contents. If asked about visual content, say that no current visual observation context is available and ask the user to provide one.
If that section is present, describe only the visual observations stated there. Do not infer unseen details, live camera access, screen access, or file inspection beyond that context."""

VISUAL_EVENT_TYPES = {
    "visual.observation",
    "vision.observation",
    "screenshot.observation",
    "screen.observation",
    "image.observation",
    "video.observation",
    "camera.observation",
    "sensor.visual_observation",
}

VISUAL_EVENT_TYPE_PREFIXES = (
    "visual.",
    "vision.",
    "screenshot.",
    "screen.",
    "image.",
    "video.",
    "camera.",
)

VISUAL_OBSERVATION_FIELDS = (
    "visual_observation",
    "visual_observations",
    "visual_description",
    "scene_description",
    "description",
    "caption",
    "summary",
    "observation",
    "observations",
    "detected_objects",
    "ocr_text",
)

# Delay before disconnecting the agent after the last human leaves.
# Exposed for tests (set to 0) and for tuning in development.
AGENT_DISCONNECT_DELAY_SECONDS = float(os.getenv("AGENT_DISCONNECT_DELAY_SECONDS", "0.5"))

# Whether to auto-create episodic memories per utterance.
# Always-on deployments typically prefer summaries/facts generated by a planner.
AUTOSAVE_EPISODIC_MEMORIES = str(os.getenv("AUTOSAVE_EPISODIC_MEMORIES", "true")).strip().lower() in (
    "true",
    "1",
    "yes",
)

# Contextual recall is intentionally not a space filter. The current space,
# session, and person bias prompt hydration ranking after agent-wide recall.
CONTEXTUAL_RECALL_K = int(os.getenv("CONTEXTUAL_RECALL_K", "16"))
CURRENT_SESSION_MEMORY_WEIGHT = 0.35
CURRENT_SPACE_MEMORY_WEIGHT = 0.2
CURRENT_PERSON_MEMORY_WEIGHT = 0.15
GENERIC_MEMORY_WEIGHT = 0.05

# Hub connection settings
HUB_API_BASE = os.getenv("HUB_API_BASE", "").rstrip("/")
HUB_DEVICE_TOKEN = os.getenv("HUB_DEVICE_TOKEN", "")


def hub_ingest_transcript(
    *,
    space_id: str,
    text: str,
    role: str,
    participant_identity: str | None = None,
    input_modality: str = "voice",
    session_id: str | None = None,
) -> str | None:
    """Send a transcript chunk to the Hub for persistence.

    Args:
        space_id: The Marvain space ID (from room name)
        text: The transcript text
        role: Either "user" or "assistant"
        participant_identity: The LiveKit participant identity
        input_modality: Either "voice" or "text"
    """
    hub_api_base = str(os.getenv("HUB_API_BASE") or HUB_API_BASE or "").rstrip("/")
    hub_device_token = str(os.getenv("HUB_DEVICE_TOKEN") or HUB_DEVICE_TOKEN or "").strip()
    if not hub_api_base or not hub_device_token or not space_id:
        logger.debug("Skipping transcript ingest: missing HUB_API_BASE, HUB_DEVICE_TOKEN, or space_id")
        return None

    try:
        resp = requests.post(
            f"{hub_api_base}/v1/events",
            headers={"Authorization": f"Bearer {hub_device_token}"},
            json={
                "space_id": space_id,
                "type": "transcript_chunk",
                "payload": {
                    "text": text,
                    "role": role,
                    "participant_identity": participant_identity,
                    "source": "livekit_agent_worker",
                    "input_modality": input_modality,
                },
                "session_id": session_id,
            },
            timeout=3,
        )
        if resp.ok:
            logger.debug(f"Ingested transcript ({role}): {text[:50]}...")
            return str(resp.json().get("event_id") or "").strip() or None
        else:
            logger.warning("Failed to ingest transcript: status=%s body=%s", resp.status_code, resp.text[:300])
    except Exception as e:
        # Don't crash the realtime loop
        logger.warning(f"Failed to ingest transcript: {e}")
    return None


def hub_create_memory(
    *,
    space_id: str,
    content: str,
    tier: str = "episodic",
    metadata: dict | None = None,
    source_event_id: str,
    session_id: str | None = None,
) -> None:
    """Create a memory in the Hub's memory system.

    Args:
        space_id: The Marvain space ID
        content: The memory content text
        tier: Memory tier (episodic, semantic, procedural)
        metadata: Additional metadata (input_modality, role, room_name, etc.)
    """
    hub_api_base = str(os.getenv("HUB_API_BASE") or HUB_API_BASE or "").rstrip("/")
    hub_device_token = str(os.getenv("HUB_DEVICE_TOKEN") or HUB_DEVICE_TOKEN or "").strip()
    if not hub_api_base or not hub_device_token or not space_id:
        logger.debug("Skipping memory creation: missing HUB_API_BASE, HUB_DEVICE_TOKEN, or space_id")
        return

    try:
        resp = requests.post(
            f"{hub_api_base}/v1/memories",
            headers={"Authorization": f"Bearer {hub_device_token}"},
            json={
                "space_id": space_id,
                "tier": tier,
                "content": content,
                "metadata": metadata or {},
                "source_event_id": source_event_id,
                "session_id": session_id,
            },
            timeout=3,
        )
        if resp.ok:
            logger.debug(f"Created memory ({tier}): {content[:50]}...")
        else:
            logger.warning("Failed to create memory: status=%s body=%s", resp.status_code, resp.text[:300])
    except Exception as e:
        logger.warning(f"Failed to create memory: {e}")


def classify_memory_for_capture(
    *,
    text: str,
    modality: str,
    source_event_id: str,
    actor_type: str,
    source: str,
    interacting_agent_id: str | None = None,
) -> list:
    """Classify auto-captured memory through the configured provider."""

    try:
        return classify_memory_event(
            text=text,
            modality=modality,
            source_evidence_id=source_event_id,
            actor_type=actor_type,
            source=source,
            interacting_agent_id=interacting_agent_id,
        )
    except MemoryClassifierUnavailable as exc:
        logger.error("Memory auto-capture classification unavailable: %s", exc)
        return []


def hub_ingest_event(
    *,
    space_id: str,
    event_type: str,
    payload: dict,
    session_id: str | None = None,
) -> str | None:
    """Persist a non-transcript session event to the Hub."""
    hub_api_base = str(os.getenv("HUB_API_BASE") or HUB_API_BASE or "").rstrip("/")
    hub_device_token = str(os.getenv("HUB_DEVICE_TOKEN") or HUB_DEVICE_TOKEN or "").strip()
    if not hub_api_base or not hub_device_token or not space_id:
        logger.debug("Skipping event ingest: missing HUB_API_BASE, HUB_DEVICE_TOKEN, or space_id")
        return None
    try:
        resp = requests.post(
            f"{hub_api_base}/v1/events",
            headers={"Authorization": f"Bearer {hub_device_token}"},
            json={
                "space_id": space_id,
                "type": event_type,
                "payload": payload,
                "session_id": session_id,
            },
            timeout=3,
        )
        if resp.ok:
            return str(resp.json().get("event_id") or "").strip() or None
        logger.warning("Failed to ingest event %s: status=%s body=%s", event_type, resp.status_code, resp.text[:300])
    except Exception as e:
        logger.warning("Failed to ingest event %s: %s", event_type, e)
    return None


def _fetch_space_events(space_id: str, limit: int = 50) -> list[dict]:
    """Fetch recent events for context hydration.

    Returns list of events or empty list on failure.
    """
    if not HUB_API_BASE or not HUB_DEVICE_TOKEN:
        return []
    try:
        resp = requests.get(
            f"{HUB_API_BASE}/v1/spaces/{space_id}/events",
            headers={"Authorization": f"Bearer {HUB_DEVICE_TOKEN}"},
            params={"limit": limit},
            timeout=5,
        )
        if resp.ok:
            return resp.json().get("events", [])
        logger.warning("Failed to fetch space events: status=%s body=%s", resp.status_code, resp.text[:300])
    except Exception as e:
        logger.warning(f"Failed to fetch space events: {e}")
    return []


def _fetch_recall_memories(
    agent_id: str, space_id: str | None, query: str, k: int = 8, person_id: str | None = None
) -> list[dict]:
    """Fetch relevant memories via semantic search.

    Returns list of memories or empty list on failure.
    """
    if not HUB_API_BASE or not HUB_DEVICE_TOKEN:
        return []
    try:
        resp = requests.post(
            f"{HUB_API_BASE}/v1/recall",
            headers={"Authorization": f"Bearer {HUB_DEVICE_TOKEN}"},
            json={
                "agent_id": agent_id,
                "space_id": space_id,
                "person_id": person_id,
                "query": query,
                "k": k,
            },
            timeout=10,
        )
        if resp.ok:
            return resp.json().get("memories", [])
        logger.warning("Failed to fetch memories: status=%s body=%s", resp.status_code, resp.text[:300])
    except Exception as e:
        logger.warning(f"Failed to fetch memories: {e}")
    return []


@dataclass(frozen=True)
class MemorySourceContext:
    source_event_id: str | None = None
    device_id: str | None = None
    space_id: str | None = None
    session_id: str | None = None
    person_id: str | None = None
    situation: str | None = None


def _dict_or_empty(value: object) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _first_nonempty(*values: object) -> str | None:
    for value in values:
        text = str(value or "").strip()
        if text:
            return text
    return None


def _memory_source_context(mem: dict) -> MemorySourceContext:
    explanation = _dict_or_empty(mem.get("explanation"))
    source_evidence = _dict_or_empty(explanation.get("source_evidence"))
    event_payload = _dict_or_empty(source_evidence.get("event_payload"))
    provenance = _dict_or_empty(explanation.get("provenance"))
    stored = _dict_or_empty(explanation.get("stored"))
    metadata = _dict_or_empty(mem.get("metadata"))

    return MemorySourceContext(
        source_event_id=_first_nonempty(
            explanation.get("source_event_id"),
            source_evidence.get("event_id"),
            mem.get("source_event_id"),
            stored.get("source_event_id"),
            event_payload.get("source_event_id"),
        ),
        device_id=_first_nonempty(
            explanation.get("device_id"),
            source_evidence.get("device_id"),
            mem.get("device_id"),
            provenance.get("device_id"),
            stored.get("device_id"),
            event_payload.get("device_id"),
            metadata.get("device_id"),
        ),
        space_id=_first_nonempty(
            explanation.get("space_id"),
            source_evidence.get("space_id"),
            mem.get("space_id"),
            stored.get("space_id"),
            event_payload.get("space_id"),
            metadata.get("space_id"),
        ),
        session_id=_first_nonempty(
            explanation.get("session_id"),
            source_evidence.get("session_id"),
            mem.get("session_id"),
            stored.get("session_id"),
            event_payload.get("session_id"),
            metadata.get("session_id"),
        ),
        person_id=_first_nonempty(
            explanation.get("person_id"),
            source_evidence.get("person_id"),
            mem.get("person_id"),
            mem.get("subject_person_id"),
            stored.get("person_id"),
            event_payload.get("person_id"),
            metadata.get("person_id"),
        ),
        situation=_first_nonempty(
            explanation.get("situation"),
            source_evidence.get("situation"),
            mem.get("situation"),
            provenance.get("situation"),
            stored.get("situation"),
            event_payload.get("situation"),
            event_payload.get("situation_id"),
            event_payload.get("activity"),
            event_payload.get("activity_context"),
            event_payload.get("location_context"),
            event_payload.get("space_name"),
            metadata.get("situation"),
        ),
    )


def _format_memory_source_note(mem: dict) -> str:
    context = _memory_source_context(mem)
    source_bits = []
    if context.source_event_id:
        source_bits.append(f"event {context.source_event_id}")
    if context.device_id:
        source_bits.append(f"device {context.device_id}")
    if context.space_id:
        source_bits.append(f"space {context.space_id}")
    if context.session_id:
        source_bits.append(f"session {context.session_id}")
    if context.person_id:
        source_bits.append(f"person {context.person_id}")
    if context.situation:
        source_bits.append(f"situation {context.situation}")
    return f" (source: {', '.join(source_bits)})" if source_bits else ""


def _memory_recall_distance(mem: dict, fallback_rank: int) -> float:
    explanation = _dict_or_empty(mem.get("explanation"))
    ranking = _dict_or_empty(explanation.get("ranking"))
    for value in (
        ranking.get("weighted_distance"),
        ranking.get("embedding_distance"),
        ranking.get("distance"),
        mem.get("distance"),
    ):
        try:
            return float(value)
        except (TypeError, ValueError):
            continue
    return float(fallback_rank)


def _dedupe_memories(memories: list[dict]) -> list[dict]:
    seen = set()
    deduped = []
    for mem in memories:
        mid = str(mem.get("memory_id") or "").strip()
        key = mid or f"{mem.get('tier')}\0{mem.get('content')}"
        if key in seen:
            continue
        seen.add(key)
        deduped.append(mem)
    return deduped


def _rank_contextual_memories(
    memories: list[dict],
    *,
    current_space_id: str | None,
    current_session_id: str | None,
    active_person_id: str | None,
    limit: int = 8,
) -> list[dict]:
    current_space_id = str(current_space_id or "").strip() or None
    current_session_id = str(current_session_id or "").strip() or None
    active_person_id = str(active_person_id or "").strip() or None
    ranked = []
    for index, mem in enumerate(_dedupe_memories(memories)):
        source = _memory_source_context(mem)
        distance = _memory_recall_distance(mem, index + 1)
        context_weight = 0.0
        if current_session_id and source.session_id == current_session_id:
            context_weight += CURRENT_SESSION_MEMORY_WEIGHT
        if current_space_id and source.space_id == current_space_id:
            context_weight += CURRENT_SPACE_MEMORY_WEIGHT
        elif current_space_id and not source.space_id:
            context_weight += GENERIC_MEMORY_WEIGHT
        if active_person_id and source.person_id == active_person_id:
            context_weight += CURRENT_PERSON_MEMORY_WEIGHT
        ranked.append((distance - context_weight, distance, index, mem))
    ranked.sort(key=lambda item: (item[0], item[1], item[2]))
    return [mem for _, _, _, mem in ranked[:limit]]


def _contextual_recall_query(
    base_query: str,
    *,
    current_space_id: str | None,
    current_session_id: str | None,
    active_person_id: str | None,
) -> str:
    context_bits = ["current live conversation"]
    if current_space_id:
        context_bits.append(f"current space {current_space_id}")
    if current_session_id:
        context_bits.append(f"current session {current_session_id}")
    if active_person_id:
        context_bits.append(f"current person {active_person_id}")
    return f"{base_query}; {'; '.join(context_bits)}"


def _fetch_contextual_recall_memories(
    *,
    agent_id: str,
    current_space_id: str,
    current_session_id: str | None,
    active_person_id: str | None,
) -> list[dict]:
    """Recall agent memories and bias ranking toward the current context.

    Passing ``space_id`` to the Hub recall endpoint filters to that space. Worker
    hydration needs broader agent memory, so the current space is carried in the
    query text and applied as local ranking context after recall.
    """
    memories: list[dict] = []
    if active_person_id:
        memories.extend(
            _fetch_recall_memories(
                agent_id=agent_id,
                space_id=None,
                person_id=active_person_id,
                query=_contextual_recall_query(
                    "facts preferences relationship history about the current speaker",
                    current_space_id=current_space_id,
                    current_session_id=current_session_id,
                    active_person_id=active_person_id,
                ),
                k=CONTEXTUAL_RECALL_K,
            )
        )
    memories.extend(
        _fetch_recall_memories(
            agent_id=agent_id,
            space_id=None,
            query=_contextual_recall_query(
                "session context recent conversation important facts",
                current_space_id=current_space_id,
                current_session_id=current_session_id,
                active_person_id=active_person_id,
            ),
            k=CONTEXTUAL_RECALL_K,
        )
    )
    return _rank_contextual_memories(
        memories,
        current_space_id=current_space_id,
        current_session_id=current_session_id,
        active_person_id=active_person_id,
    )


def _infer_active_person_id(events: list[dict]) -> str | None:
    """Best-effort: infer the current human speaker from recent transcript events.

    The Hub can map LiveKit participant identities to people via person_accounts,
    populating events.person_id for transcript_chunk events. We use the newest
    user transcript with a person_id as a hint for person-scoped recall.
    """
    for ev in events or []:
        if ev.get("type") != "transcript_chunk":
            continue
        payload = ev.get("payload") or {}
        if isinstance(payload, dict) and payload.get("role") == "user":
            pid = str(ev.get("person_id") or "").strip()
            if pid:
                return pid
    return None


def _event_matches_session(ev: dict, current_session_id: str | None) -> bool:
    if not current_session_id:
        return False
    event_session_id = str(ev.get("session_id") or "").strip()
    if event_session_id == current_session_id:
        return True
    payload = ev.get("payload") if isinstance(ev.get("payload"), dict) else {}
    payload_session_id = str(payload.get("session_id") or "").strip()
    return payload_session_id == current_session_id


def _event_type_is_visual_observation(event_type: str) -> bool:
    normalized = str(event_type or "").strip().lower().replace("_", ".")
    if normalized in VISUAL_EVENT_TYPES:
        return True
    return any(
        normalized.startswith(prefix) and normalized.endswith(".observation") for prefix in VISUAL_EVENT_TYPE_PREFIXES
    )


def _format_visual_observation_value(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, (int, float, bool)):
        return str(value)
    if isinstance(value, list):
        return ", ".join(str(item).strip() for item in value if str(item).strip())
    if isinstance(value, dict):
        parts = []
        for key, item in value.items():
            text = _format_visual_observation_value(item)
            if text:
                parts.append(f"{key}: {text}")
        return "; ".join(parts)
    return str(value).strip()


def _extract_visual_observation_text(ev: dict) -> str:
    payload = ev.get("payload") if isinstance(ev.get("payload"), dict) else {}
    for field in VISUAL_OBSERVATION_FIELDS:
        text = _format_visual_observation_value(payload.get(field))
        if text:
            return text
    return ""


def _extract_openai_response_text(resp: dict) -> str:
    texts: list[str] = []
    for item in resp.get("output") or []:
        if not isinstance(item, dict):
            continue
        for content in item.get("content") or []:
            if not isinstance(content, dict):
                continue
            text = content.get("text")
            if text:
                texts.append(str(text).strip())
    return "\n".join(t for t in texts if t).strip()


def _describe_visual_artifact(artifact_uri: str) -> str | None:
    """Describe a current-session visual artifact with OpenAI vision.

    Returning ``None`` keeps the truthfulness guard closed: artifact references
    alone are not visual observations.
    """
    artifact_uri = str(artifact_uri or "").strip()
    api_key = str(os.getenv("OPENAI_API_KEY") or "").strip()
    if not artifact_uri or not api_key or not artifact_uri.startswith("s3://"):
        return None

    try:
        import base64
        import urllib.parse

        import boto3

        parsed = urllib.parse.urlparse(artifact_uri)
        bucket = parsed.netloc
        key = parsed.path.lstrip("/")
        if not bucket or not key:
            return None

        s3 = boto3.client("s3")
        obj = s3.get_object(Bucket=bucket, Key=key)
        image_bytes = obj["Body"].read(4_000_001)
        if len(image_bytes) > 4_000_000:
            logger.warning("Skipping visual description: artifact exceeds size limit")
            return None

        content_type = str(obj.get("ContentType") or "image/jpeg")
        image_data_url = f"data:{content_type};base64,{base64.b64encode(image_bytes).decode('ascii')}"
        response = requests.post(
            "https://api.openai.com/v1/responses",
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            json={
                "model": os.getenv("OPENAI_VISION_MODEL", "gpt-4.1-mini"),
                "input": [
                    {
                        "role": "system",
                        "content": [
                            {
                                "type": "input_text",
                                "text": (
                                    "You produce concise, objective visual observations for a live assistant. "
                                    "Describe only visible facts in the image. Do not infer identities, private "
                                    "attributes, or unavailable context."
                                ),
                            }
                        ],
                    },
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "input_text",
                                "text": "Describe the current camera frame in one or two short sentences.",
                            },
                            {"type": "input_image", "image_url": image_data_url},
                        ],
                    },
                ],
                "max_output_tokens": 160,
            },
            timeout=20,
        )
        if not response.ok:
            logger.warning(
                "Visual description request failed: status=%s body=%s", response.status_code, response.text[:200]
            )
            return None
        text = _extract_openai_response_text(response.json())
        return text[:800] if text else None
    except Exception as exc:
        logger.warning("Failed to describe visual artifact: %s", exc.__class__.__name__)
        return None


def _build_current_visual_observation_block(events: list[dict], *, current_session_id: str | None) -> str:
    """Build same-session textual visual observations for the model prompt.

    Artifact-only events are intentionally ignored here. A screenshot/image/video
    reference is not visual access until another component has produced textual
    observation context for this exact session.
    """
    observations = []
    for ev in events or []:
        if not _event_matches_session(ev, current_session_id):
            continue
        if not _event_type_is_visual_observation(str(ev.get("type") or "")):
            continue
        text = _extract_visual_observation_text(ev)
        if not text:
            continue
        observations.append(text[:500])
        if len(observations) >= 5:
            break
    if not observations:
        return ""
    lines = ["## Current Session Visual Observations"]
    lines.extend(f"- {text}" for text in observations)
    return "\n".join(lines)


def _build_context_block(events: list[dict], memories: list[dict], *, current_session_id: str | None = None) -> str:
    """Build context block for agent instructions.

    Summarizes recent conversation and relevant memories.
    """
    parts = []

    visual_context = _build_current_visual_observation_block(events, current_session_id=current_session_id)
    if visual_context:
        parts.append(visual_context)

    # Add memory context if available
    if memories:
        parts.append("## Relevant Memories")
        for mem in memories[:5]:  # Limit to top 5
            tier = mem.get("tier", "")
            content = mem.get("content", "")[:500]  # Truncate long content
            source_note = _format_memory_source_note(mem)
            parts.append(f"- [{tier}] {content}{source_note}")

    # Add recent conversation summary if available
    if events:
        parts.append("\n## Recent Conversation in This Space")
        # Group by role and summarize - show last 10 events max
        for ev in reversed(events[:10]):
            payload = ev.get("payload", {})
            role = payload.get("role", "unknown")
            text = payload.get("text", "")[:200]  # Truncate
            if text and ev.get("type") == "transcript_chunk":
                speaker = "User" if role == "user" else "You"
                parts.append(f"- {speaker}: {text}")

    if not parts:
        return ""

    return "\n".join(parts)


@dataclass(frozen=True)
class PersonaConfig:
    persona_id: str | None
    name: str
    instructions: str
    source: str


class ForgeAssistant(Agent):
    def __init__(self, *, persona: PersonaConfig, context_block: str = "") -> None:
        persona_instructions = persona.instructions.strip()
        if not persona_instructions:
            raise RuntimeError("persona instructions are empty")
        persona_instructions = f"{persona_instructions}\n\n{VISUAL_TRUTHFULNESS_GUARD}"
        if context_block:
            instructions = f"{persona_instructions}\n\n# Context from Prior Sessions\n{context_block}"
        else:
            instructions = persona_instructions
        super().__init__(instructions=instructions)


def _resolve_persona(*, agent_id: str | None, space_id: str, session_id: str | None) -> PersonaConfig:
    """Resolve the configured persona for this agent session."""
    env_instructions = str(os.getenv("MARVAIN_AGENT_PERSONA_INSTRUCTIONS") or "").strip()
    if env_instructions:
        return PersonaConfig(
            persona_id=None,
            name=str(os.getenv("MARVAIN_AGENT_PERSONA_NAME") or DEFAULT_AGENT_PERSONA_NAME).strip()
            or DEFAULT_AGENT_PERSONA_NAME,
            instructions=env_instructions,
            source="env",
        )

    if not agent_id:
        raise RuntimeError("persona resolution requires agent_id in LiveKit dispatch metadata")

    hub_api_base = str(os.getenv("HUB_API_BASE") or HUB_API_BASE or "").rstrip("/")
    hub_device_token = str(os.getenv("HUB_DEVICE_TOKEN") or HUB_DEVICE_TOKEN or "").strip()
    if not hub_api_base or not hub_device_token:
        raise RuntimeError("persona resolution requires HUB_API_BASE and HUB_DEVICE_TOKEN")

    resp = requests.get(
        f"{hub_api_base}/v1/agents/{agent_id}/personas/default",
        headers={"Authorization": f"Bearer {hub_device_token}"},
        params={"space_id": space_id, "session_id": session_id or ""},
        timeout=5,
    )
    if not resp.ok:
        raise RuntimeError(f"persona lookup failed: status={resp.status_code} body={resp.text[:300]}")
    body = resp.json()
    instructions = str(body.get("instructions") or "").strip()
    if not instructions:
        raise RuntimeError("persona lookup returned empty instructions")
    return PersonaConfig(
        persona_id=str(body.get("persona_id") or "").strip() or None,
        name=str(body.get("name") or DEFAULT_AGENT_PERSONA_NAME).strip() or DEFAULT_AGENT_PERSONA_NAME,
        instructions=instructions,
        source=str(body.get("source") or "hub"),
    )


# Agent name for explicit dispatch - must match the name in tokens minted by Hub API
AGENT_NAME = "forge"

server = AgentServer()


@server.rtc_session(agent_name=AGENT_NAME)
async def forge_agent(ctx: agents.JobContext):
    """Handle a LiveKit agent session for a Marvain space.

    Room names are ephemeral: "{space_id}:{session_id}". The space_id is passed
    via agent dispatch metadata so we can persist transcripts to the correct space.

    When the last human participant leaves, the agent disconnects from the room.
    Since each join creates a unique room name, agent dispatch is reliable.
    """
    # Connect to LiveKit room
    await ctx.connect()

    # Extract space_id from agent metadata (passed via RoomAgentDispatch in token)
    # Metadata is a JSON string in ctx.job.metadata
    import json as _json

    metadata = _json.loads(ctx.job.metadata or "{}")
    space_id = metadata.get("space_id")
    room_session_id = metadata.get("room_session_id", "unknown")
    session_id = metadata.get("session_id")

    if not space_id:
        logger.error(f"No space_id in agent metadata; room={ctx.room.name}, metadata={ctx.job.metadata}")
        return

    agent_id = metadata.get("agent_id")
    logger.info(f"Agent dispatched to space: {space_id} (room: {ctx.room.name}, session: {room_session_id})")
    persona = _resolve_persona(agent_id=agent_id, space_id=space_id, session_id=session_id)
    logger.info(
        "Resolved persona %s for session %s from %s", persona.name, session_id or room_session_id, persona.source
    )

    # Context hydration: fetch prior events and memories for continuity
    context_block = ""
    if agent_id and HUB_API_BASE and HUB_DEVICE_TOKEN:
        logger.info(f"Fetching context for space {space_id}...")
        events = _fetch_space_events(space_id, limit=50)
        active_person_id = _infer_active_person_id(events)
        memories = _fetch_contextual_recall_memories(
            agent_id=agent_id,
            current_space_id=space_id,
            current_session_id=session_id,
            active_person_id=active_person_id,
        )
        context_block = _build_context_block(events, memories, current_session_id=session_id)
        if context_block:
            logger.info(f"Context hydration: {len(events)} events, {len(memories)} memories")
        else:
            logger.debug("No prior context found for this space")

    # Track whether we should auto-disconnect when humans leave
    should_disconnect_on_empty = True

    def count_human_participants() -> int:
        """Count non-agent participants in the room."""
        count = 0
        for participant in ctx.room.remote_participants.values():
            if participant.kind != rtc.ParticipantKind.PARTICIPANT_KIND_AGENT:
                count += 1
        return count

    def on_participant_disconnected(participant: rtc.RemoteParticipant) -> None:
        """Handle participant disconnection - disconnect agent if no humans remain."""
        if not should_disconnect_on_empty:
            return

        # Skip if an agent disconnected (we only care about humans leaving)
        if participant.kind == rtc.ParticipantKind.PARTICIPANT_KIND_AGENT:
            logger.debug(f"Agent participant disconnected: {participant.identity}")
            return

        logger.info(f"Human participant disconnected: {participant.identity}")

        # Check if any human participants remain
        human_count = count_human_participants()
        logger.info(f"Remaining human participants: {human_count}")

        if human_count == 0:
            logger.info(f"No human participants remain in room {space_id}, agent disconnecting...")
            # Schedule disconnect - don't block the event handler
            asyncio.create_task(_disconnect_agent())

    async def _disconnect_agent() -> None:
        """Disconnect the agent from the room."""
        try:
            # Small delay to allow any final cleanup
            await asyncio.sleep(AGENT_DISCONNECT_DELAY_SECONDS)
            await ctx.room.disconnect()
            logger.info(f"Agent disconnected from room {space_id}")
        except Exception as e:
            logger.warning(f"Error disconnecting agent from room {space_id}: {e}")

    # Subscribe to participant disconnection events
    ctx.room.on("participant_disconnected", on_participant_disconnected)

    # Realtime model (speech-to-speech). Configure voice via env.
    voice = os.getenv("OPENAI_VOICE", "alloy")
    model = os.getenv("OPENAI_REALTIME_MODEL", "gpt-4o-realtime-preview")

    session = AgentSession(
        llm=openai.realtime.RealtimeModel(
            model=model,
            voice=voice,
        )
    )

    # Wire up transcript ingestion - forward conversation items to Hub
    from livekit.agents.voice import ConversationItemAddedEvent, UserInputTranscribedEvent

    def on_conversation_item_added(event: ConversationItemAddedEvent) -> None:
        """Forward transcript chunks to the Hub for persistence."""
        item = event.item
        # Only process ChatMessage items, skip type discriminators
        if not hasattr(item, "role") or not hasattr(item, "text_content"):
            return

        role = item.role
        text = item.text_content

        # Only ingest assistant messages here. User voice transcripts are handled
        # via UserInputTranscribedEvent so we can attach speaker_id.
        if role != "assistant" or not text:
            return

        logger.debug(f"Conversation item ({role}): {text[:50]}...")
        source_event_id = hub_ingest_transcript(
            space_id=space_id,
            text=text,
            role=role,
            participant_identity=None,
            input_modality="voice",
            session_id=session_id,
        )
        if AUTOSAVE_EPISODIC_MEMORIES:
            # Auto-save as episodic memory
            if source_event_id and source_event_id != "privacy_mode":
                for classification in classify_memory_for_capture(
                    text=text,
                    modality="audio",
                    source_event_id=source_event_id,
                    actor_type="agent",
                    source="livekit_assistant_voice",
                ):
                    hub_create_memory(
                        space_id=space_id,
                        content=text,
                        tier=classification.kind,
                        metadata={
                            "role": role,
                            "input_modality": "voice",
                            "room_name": ctx.room.name,
                            "room_session_id": room_session_id,
                            "memory_classification": classification.as_metadata(),
                        },
                        source_event_id=source_event_id,
                        session_id=session_id,
                    )

    session.on("conversation_item_added", on_conversation_item_added)

    def on_user_input_transcribed(event: UserInputTranscribedEvent) -> None:
        """Ingest final user voice transcripts with speaker identity."""
        if not event.is_final:
            return
        text = str(event.transcript or "").strip()
        if not text:
            return

        participant_identity = str(event.speaker_id or "").strip() or None
        source_event_id = hub_ingest_transcript(
            space_id=space_id,
            text=text,
            role="user",
            participant_identity=participant_identity,
            input_modality="voice",
            session_id=session_id,
        )
        if AUTOSAVE_EPISODIC_MEMORIES:
            if source_event_id and source_event_id != "privacy_mode":
                for classification in classify_memory_for_capture(
                    text=text,
                    modality="audio",
                    source_event_id=source_event_id,
                    actor_type="user",
                    source="livekit_user_voice",
                ):
                    hub_create_memory(
                        space_id=space_id,
                        content=text,
                        tier=classification.kind,
                        metadata={
                            "role": "user",
                            "input_modality": "voice",
                            "room_name": ctx.room.name,
                            "room_session_id": room_session_id,
                            "participant_identity": participant_identity,
                            "memory_classification": classification.as_metadata(),
                        },
                        source_event_id=source_event_id,
                        session_id=session_id,
                    )

    session.on("user_input_transcribed", on_user_input_transcribed)

    # Handle typed chat messages from data channel
    import json as _json_dc

    current_visual_observations: list[str] = []

    def _current_visual_prompt() -> str:
        if not current_visual_observations:
            return ""
        lines = ["Current Session Visual Observations:"]
        lines.extend(f"- {text}" for text in current_visual_observations[-3:])
        return "\n".join(lines)

    async def _publish_visual_observation_ack(payload: dict[str, object]) -> None:
        participant = getattr(ctx.room, "local_participant", None)
        publish_data = getattr(participant, "publish_data", None)
        if publish_data is None:
            return
        try:
            result = publish_data(_json_dc.dumps(payload).encode("utf-8"), reliable=True)
            if asyncio.iscoroutine(result):
                await result
        except Exception as exc:
            logger.warning("Failed to publish visual observation acknowledgement: %s", exc)

    async def _process_visual_observation_message(
        *, sender: str, artifact_uri: str, captured_at: str, visual_request_id: str
    ) -> None:
        observation = ""
        if not observation and artifact_uri:
            described = await asyncio.to_thread(_describe_visual_artifact, artifact_uri)
            observation = str(described or "").strip()

        if not observation:
            logger.info("Ignoring visual_observation from %s without analyzed observation text", sender)
            hub_ingest_event(
                space_id=space_id,
                event_type="visual.artifact_reference",
                payload={
                    "source": "livekit_browser_camera",
                    "artifact_uri": artifact_uri,
                    "captured_at": captured_at,
                    "visual_request_id": visual_request_id,
                    "participant_identity": sender,
                    "truthfulness_note": "artifact reference only; no visual observation text",
                },
                session_id=session_id,
            )
            await _publish_visual_observation_ack(
                {
                    "type": "visual_observation_ack",
                    "ok": False,
                    "error": "camera_enabled_but_visual_analysis_unavailable",
                    "visual_request_id": visual_request_id,
                    "artifact_uri": artifact_uri,
                    "captured_at": captured_at,
                }
            )
            return

        observation = observation[:800]
        current_visual_observations.append(observation)
        del current_visual_observations[:-5]
        hub_ingest_event(
            space_id=space_id,
            event_type="visual.observation",
            payload={
                "source": "livekit_browser_camera",
                "description": observation,
                "artifact_uri": artifact_uri,
                "captured_at": captured_at,
                "visual_request_id": visual_request_id,
                "participant_identity": sender,
                "model": os.getenv("OPENAI_VISION_MODEL", "gpt-4.1-mini") if artifact_uri else None,
            },
            session_id=session_id,
        )
        logger.info("Recorded visual observation from %s", sender)
        await _publish_visual_observation_ack(
            {
                "type": "visual_observation_ack",
                "ok": True,
                "visual_request_id": visual_request_id,
                "description": observation,
                "artifact_uri": artifact_uri,
                "captured_at": captured_at,
            }
        )

    @ctx.room.on("data_received")
    def on_data_received(data: rtc.DataPacket) -> None:
        """Handle typed chat messages from participants.

        When a user types a message in the chat UI, it's sent via LiveKit's
        data channel. We parse it and inject it into the conversation as if
        the user had spoken it.
        """
        try:
            payload = data.data.decode("utf-8")
            msg = _json_dc.loads(payload)
            msg_type = str(msg.get("type") or "").strip()
            sender = data.participant.identity if data.participant else "user"

            if msg_type == "visual_observation":
                artifact_uri = str(msg.get("artifact_uri") or "").strip()
                captured_at = str(msg.get("captured_at") or msg.get("ts") or "").strip()
                visual_request_id = str(msg.get("visual_request_id") or "").strip()
                asyncio.create_task(
                    _process_visual_observation_message(
                        sender=sender,
                        artifact_uri=artifact_uri,
                        captured_at=captured_at,
                        visual_request_id=visual_request_id,
                    )
                )
                return

            # Only handle chat messages
            if msg_type != "chat":
                return

            text = msg.get("text", "").strip()
            if not text:
                return

            logger.info(f"Received typed chat from {sender}: {text[:50]}...")

            # Ingest to Hub for persistence
            source_event_id = hub_ingest_transcript(
                space_id=space_id,
                text=text,
                role="user",
                participant_identity=sender,
                input_modality="text",
                session_id=session_id,
            )
            if AUTOSAVE_EPISODIC_MEMORIES:
                # Auto-save as episodic memory
                if source_event_id and source_event_id != "privacy_mode":
                    for classification in classify_memory_for_capture(
                        text=text,
                        modality="text",
                        source_event_id=source_event_id,
                        actor_type="user",
                        source="livekit_typed_chat",
                    ):
                        hub_create_memory(
                            space_id=space_id,
                            content=text,
                            tier=classification.kind,
                            metadata={
                                "role": "user",
                                "input_modality": "text",
                                "room_name": ctx.room.name,
                                "room_session_id": room_session_id,
                                "participant_identity": sender,
                                "memory_classification": classification.as_metadata(),
                            },
                            source_event_id=source_event_id,
                            session_id=session_id,
                        )

            # Inject the typed message into the agent's conversation
            # Use generate_reply with the user's text as instructions
            asyncio.create_task(_handle_typed_message(text, sender))

        except Exception as e:
            logger.warning(f"Failed to process data channel message: {e}")

    async def _handle_typed_message(text: str, sender: str) -> None:
        """Process a typed chat message and generate a response.

        Interrupts any ongoing speech before responding to avoid overlapping voices.
        Uses user_input parameter to properly inject the message into the conversation
        history, so the agent responds to the typed message (not the last voice input).
        """
        try:
            # Interrupt any ongoing speech to avoid overlapping voices
            session.interrupt()

            # Small delay to let the interruption take effect
            await asyncio.sleep(0.1)

            # Use generate_reply with user_input to inject the typed message
            # into the conversation as a proper user turn. This ensures the agent
            # responds to this message, not the last voice input.
            visual_prompt = _current_visual_prompt()
            user_input = f"{visual_prompt}\n\nUser message: {text}" if visual_prompt else text
            await session.generate_reply(user_input=user_input)
        except Exception as e:
            logger.warning(f"Failed to generate reply for typed message: {e}")

    await session.start(
        room=ctx.room,
        agent=ForgeAssistant(persona=persona, context_block=context_block),
        room_options=room_io.RoomOptions(
            audio_input=room_io.AudioInputOptions(
                noise_cancellation=lambda params: (
                    noise_cancellation.BVCTelephony()
                    if params.participant.kind == rtc.ParticipantKind.PARTICIPANT_KIND_SIP
                    else noise_cancellation.BVC()
                ),
            ),
            # Disable auto-close so our disconnect handler fires properly
            close_on_disconnect=False,
            # Do NOT delete room on close - the Hub API handles room deletion
            # before minting tokens. This ensures a single deletion point and
            # avoids race conditions with LiveKit Cloud's dispatch logic.
            delete_room_on_close=False,
        ),
    )

    # Initial greeting
    await session.generate_reply(instructions="Greet the user and offer your assistance. Start by speaking in English.")


if __name__ == "__main__":
    agents.cli.run_app(server)
